### ISSUE TITLE
Crashing on Fabric 0.14.24

### ISSUE THREAD

**Issue by C4uTi0N** [ishland/EarlyLoadingScreen#12]
[11:55:07] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.24
[11:55:07] [main/INFO]: Loading 4 mods:
	- earlyloadingscreen 0.1.2
	- fabricloader 0.14.24
	- java 17
	- minecraft 1.20.1
[11:55:08] [EarlyLoadingScreen - Render Thread/ERROR]: Uncaught exception in thread "EarlyLoadingScreen - Render Thread"
java.lang.NullPointerException: null
	at org.lwjgl.system.Checks.check(Checks.java:188) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.Callbacks.glfwFreeCallbacks(Callbacks.java:31) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.ishland.earlyloadingscreen.LoadingScreenManager$WindowEventLoop.run(LoadingScreenManager.java:406) ~[earlyloadingscreen-mc1.20.1-0.1.2-all.jar:?]
[11:55:08] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/petec/AppData/Roaming/gdlauncher_next/datastore/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[11:55:08] [main/INFO]: Compatibility level set to JAVA_17
[11:55:08] [main/ERROR]: Unable to register injection point com.ishland.earlyloadingscreen.MixinEarlyLaunch for earlyloadingscreen.mixins.json, class is not assignable to class org.spongepowered.asm.mixin.injection.InjectionPoint
[11:55:15] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on earlyloadingscreen.mixins.json:progress.MixinTextureStitcher from mod earlyloadingscreen::handler$zzg000$earlyloadingscreen$monitorStitch exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.

**Comment by C4uTi0N** [comment]
Still crashing 
[latest log.log](https://github.com/ishland/EarlyLoadingScreen/files/13166366/latest.log.log)
[crash-2023-10-25_15.16.01-client.txt](https://github.com/ishland/EarlyLoadingScreen/files/13166368/crash-2023-10-25_15.16.01-client.txt)

**Comment by ishland** [comment]
Are you sure you are testing with the version from [here](https://github.com/ishland/EarlyLoadingScreen/actions/runs/6639152523)? Extract before adding to mods folder.

**Comment by C4uTi0N** [comment]
ah i wasn't, my bad!
seems to work now on a clean version of Fabric!

However on my (heavily) modded client/version it crashes after loading through the early loading screen
[crash-2023-10-25_15.57.10-client.txt](https://github.com/ishland/EarlyLoadingScreen/files/13166868/crash-2023-10-25_15.57.10-client.txt)
[latest.log](https://github.com/ishland/EarlyLoadingScreen/files/13166870/latest.log)

Idk if this is due to some other mod messing with it or not (without ELS, it works fine)

**Comment by ishland** [comment]
You might be having some problem with `valhelsia_core`. ELS runs through all mixins and crashes early if an error is found. You can disable this behavior with `enable_mixin_pretransform` in the config file.

**Comment by C4uTi0N** [comment]
that seems to have fixed it, thanks!
